<?php

namespace Tests\Feature;

use App\Account;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;

class AccountsTest extends TestCase
{
    use DatabaseMigrations;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->seed(\BanksTableSeeder::class);
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testApiList()
    {
        $data = factory(Account::class, 20)->create();

        $response = $this->get('/api/accounts');

        $response->assertStatus(200)
            ->assertJson(['data' => $data->toArray()]);
    }


}
